from django.contrib import admin
from attendance import models

# Register your models here.
admin.site.register(models.college)
admin.site.register(models.cse1)
admin.site.register(models.cse2)
admin.site.register(models.cse3)
admin.site.register(models.cse4)
admin.site.register(models.it1)
admin.site.register(models.it2)
admin.site.register(models.it3)
admin.site.register(models.it4)
admin.site.register(models.ece1)
admin.site.register(models.ece2)
admin.site.register(models.ece3)
admin.site.register(models.ece4)
admin.site.register(models.eee1)
admin.site.register(models.eee2)
admin.site.register(models.eee3)
admin.site.register(models.eee4)
admin.site.register(models.civil1)
admin.site.register(models.civil2)
admin.site.register(models.civil3)
admin.site.register(models.civil4)
admin.site.register(models.mech1)
admin.site.register(models.mech2)
admin.site.register(models.mech3)
admin.site.register(models.mech4)

